version: 0.2

phases:
  pre_build:
    commmands:
      - apt update
      - apt install default-jdk
      - apt install maven
  build:
    commands:
      - mvn clean package
 
artifacts:
  files:
    - '**/*'
  
