version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
      
  pre_build:
    commmands:
      - apt update
      
  build:
    commands:
      - mvn install
      
artifacts:
  files:
    - '**/*'
  
